#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# shellcheck shell=bash disable=SC1091,SC2039,SC2166
#
#  template - Template file for Void pkgname
#  Created: 2024/12/05 - 10:03
#  Altered: 2024/12/05 - 10:03
#  Updated: 2025/01/19 - 00:16
#
#  Copyright (c) 2024-2025, Vilmar Catafesta <vcatafesta@gmail.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
# Template file for 'chili-pkgname'
pkgname=chili-pkgname
version=$(date +%Y%m%d)
revision=$(date +%H%M)
noarch=true
#build_style=gnu-makefile
#depends="gtk+3 gnome-bluetooth python3-setproctitle rfkill xapps"
#hostmakedepends="gettext"
hostmakedepends="git"
short_desc="Chili PKGBUILD and template for VoidLinux"
maintainer="Vilmar Catafesta <vcatafesta@gmail.com>"
license="MIT"
homepage="https://github.com/chililinux/${pkgname}"
#distfiles="${homepage}/archive/$version/$pkgname-$version.tar.gz"
#checksum=37a5b0bc3c7cbccee625209b9196a2e2966396cfe5c7652318559642fb6a7a32
wrksrc=${pkgname}

do_fetch() {
	git clone --depth 1 ${homepage} ${wrksrc}
	cd ${wrksrc}
	git checkout main
}

do_install() {
  vcopy etc /
  vcopy usr /
}
